name: Gobz Back CI/CD

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.11

      - name: Build with Maven
        run: mvn clean package --file pom.xml

  push:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      DOCKER_HUB_REPO: dodoworkshop/gobz-api
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Get project version
        run: |
          echo "RELEASE_VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV

      - name: Add SNAPSHOP for dev branch
        if: github.ref == 'refs/heads/develop'
        run: |
          RELEASE_VERSION=${{ env.RELEASE_VERSION }}-SNAPSHOT
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

      - name: Connect to Docker Hub
        run: docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}

      - name: Build docker image
        run: |
          IMAGE_TAG=${{ env.DOCKER_HUB_REPO }}:${{ env.RELEASE_VERSION }}
          ls -la
          docker build -t ${IMAGE_TAG} .

      - name: Push docker image
        run: |
          docker push ${IMAGE_TAG}